### ISSUE TITLE
Cloud-carbon-footprint / backstage-AWS

### ISSUE THREAD

**Issue by Satya7340** [cloud-carbon-footprint/ccf-backstage-plugin#70]
I am getting error while installing CCF plugin in Backstage trying to fetch details from AWS. Kindly assist 

Error: Request failed with status code 500 at createError (webpack-internal:///../../node_modules/@cloud-carbon-footprint/client/node_modules/axios/lib/core/createError.js:16:15) at settle (webpack-internal:///../../node_modules/@cloud-carbon-footprint/client/node_modules/axios/lib/core/settle.js:17:12) at XMLHttpRequest.onloadend (webpack-internal:///../../node_modules/@cloud-carbon-footprint/client/node_modules/axios/lib/adapters/xhr.js:66:7)
<img width="737" alt="CCF-error" src="https://user-images.githubusercontent.com/39889634/231080893-a0b9eb94-5ee9-489d-870f-ae4681936840.png">

**Comment by camcash17** [comment]
Hi @Satya7340, thanks for submitting this issue! Could you please provide the following information to help us understand this problem?

- The installation steps you are following to replicate this issue?
- The API request being sent to request footprint data (this can be found on the Network tab of your inspector tools when you load the page)
- The versions of backstage and also the CCF plugin you are using (We recommend using the latest versions of both)

Thanks!

**Comment by Satya7340** [comment]
Hi @camcash17, Thanks for responding. Please find the details below:

1. The installation steps you are following to replicate this issue?

I was following this for AWS integration with CCF.

https://www.cloudcarbonfootprint.org/docs/aws/

2. The versions of backstage and also the CCF plugin you are using:

Backstage version: 1.12.1
CCF plugin: 0.1.1

I see plugin installation is working fine, but as I am trying to integrate it with AWS and generate CUR report using Athena, this is not working and it's throwing error while starting backstage service. Could you please help me with app-config.yaml configuration for AWS Athena? Also, if any additional steps I might be missing for this.

**Comment by camcash17** [comment]
Hi @Satya7340 , can you please refer to [this documentation](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/plugins/backend/README.md#aws) and make sure you app-yaml config is correct?

**Comment by ccasher** [comment]
Hi @Satya7340 - I will close this issue since this thread has gone stale. Happy to re-open if you are still seeing problems!
